services:
  server:
    image: ghcr.io/v3lmx/osc_server:latest
    ports: 
      - "11001:9000"
    networks:
      - "app_network"

  web:
    image: ghcr.io/v3lmx/osc_web:latest
    ports:
      - "11443:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - "app_network"
    command: caddy file-server --root /srv --access-log

volumes:
  caddy_data:
  caddy_config:

networks: 
  app_network: 
    name: app_network
    external: true
