---
- name: Setup CI/CD user 'bot' with SSH key and Docker permissions
  hosts: all
  become: yes
  vars:
    bot_user: "bot"
    bot_ssh_key: "{{ lookup('file', 'secrets/bot.pub') }}"

  tasks:
    - name: Ensure the 'bot' user is present
      user:
        name: "{{ bot_user }}"
        state: present
        shell: /bin/bash

    - name: Ensure the '.ssh' directory exists for the 'bot' user
      file:
        path: "/home/{{ bot_user }}/.ssh"
        state: directory
        owner: "{{ bot_user }}"
        group: "{{ bot_user }}"
        mode: '0700'

    - name: Add the SSH public key to the 'bot' user's authorized_keys
      authorized_key:
        user: "{{ bot_user }}"
        state: present
        key: "{{ bot_ssh_key }}"

    - name: Ensure the 'bot' user is added to the 'docker' group
      user:
        name: "{{ bot_user }}"
        groups: docker
        append: yes
