skip_clone: true

when:
  - event: manual

steps:
  - name: build
    image: debian
    commands:
      - echo "test test test "
  - name: a-test-step
    image: golang:1.23
    commands:
      - ls
      - go get .
      - go build ./cmd/counter
