name: build and push docker

on:
  push:
    branches: ['main', 'ci']
  workflow_dispatch:

jobs:
  wg:
    needs: setup
    uses: ./.github/workflows/wg.yml
    with:
      client_ip: ${{ vars.WIREGUARD_CLIENT_IP }}
      server_ip: ${{ vars.WIREGUARD_SERVER_IP }}
      port: ${{ vars.WIREGUARD_PORT }}
      allowed_ips: ${{ vars.WIREGUARD_ALLOWED_IPS }}
      server_public_key: ${{ vars.WIREGUARD_SERVER_PUBLIC_KEY }}
    secrets:
      server_public_ip: ${{ secrets.SERVER_IP }}
      server_private_url: ${{ secrets.SERVER_PRIVATE_URL }}
      private_key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}

  push:
    needs: wg
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build Docker image
        run: |
          nix build -L --accept-flake-config .#container
          [ ! -L result ] && exit 1

      - name: Load Docker image
        run: docker load < result

      - name: Tag Docker image
        run: docker tag ${{ vars.IMAGE_NAME }}:latest "${{ secrets.REGISTRY }}"/${{ vars.IMAGE_NAME }}:latest

      - name: Push Docker image
        run: docker push "${{ secrets.REGISTRY }}"/${{ vars.IMAGE_NAME }}:latest
