name: deploy

on:
  workflow_call:
    inputs:
      deploy_env:
        description: 'deployment environment (staging/prod)'
        required: true
        type: string

name: deploy {{ inputs.deploy_env }}
  server:
    uses: ./.github/workflows/server.yml
    with: 
      image_name: osc_server_{{ inputs.deploy_env }}
      deploy_env: {{ inputs.deploy_env }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

  web:
    uses: ./.github/workflows/web.yml
    with: 
      image_name: osc_web_{{ inputs.deploy_env }}
      deploy_env: {{ inputs.deploy_env }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

  deploy:
    runs-on: ubuntu-latest
    needs: [server, web]
    environment: {{ inputs.deploy_env }}
    steps:
      - name: deploy with ssh
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: bot
          key: ${{ secrets.SSH_PRIVATE }}
          port: ${{ secrets.SSH_PORT }} 
          script: |
            mkdir -p $HOME/{{ inputs.deploy_env }}
            cd $HOME/{{ inputs.deploy_env }}
            curl -o compose.yml https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker/compose-{{ inputs.deploy_env }}.yml
            docker-compose pull
            docker-compose up -d --force-recreate
