name: deploy

on:
  push:
    branches: 
      - main
      - cicd
    types: 
      - completed
  # tags:
  #   - "[0-9].[0-9]+.[0-9]+"
  #   - "test.[0-9].[0-9]+.[0-9]+"
  
jobs:
  server:
    uses: ./.github/workflows/server.yml
    with: 
      image_name: osc_server

  web:
    uses: ./.github/workflows/web.yml
    with: 
      image_name: osc_web

  deploy:
    runs-on: ubuntu-latest
    needs: [server, web]
    environment: staging
    steps:
      - name: deploy with ssh
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: bot
          key: ${{ secrets.SSH_PRIVATE }}
          port: ${{ secrets.SSH_PORT }} 
          script: |
            mkdir -p $HOME/staging
            cd $HOME/staging
            curl -o compose.yml https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker/compose-staging.yml
            docker-compose pull
            docker-compose up -d --force-recreate
