name: Deploy osc to VPS

on:
  push:
    branches:
      - main
      - cicd
  # tags:
  #   - "[0-9].[0-9]+.[0-9]+"
  #   - "test.[0-9].[0-9]+.[0-9]+"
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: deploy with ssh
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: bot
          key: ${{ secrets.SSH_PRIVATE }}
          port: ${{ secrets.SSH_PORT }} 
          script: |
            mkdir -p $HOME/staging
            cd $HOME/staging
            curl -o compose.yml https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/compose-staging.yml
            docker-compose pull
            docker-compose up -d
