name: Docker

on:
  push:
    branches: ['main', 'ci']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build Docker image
        id: build
        run: |
          nix build -L --accept-flake-config .#container
          [ ! -L result ] && exit 1
          echo "path=$(realpath result)" >> "$GITHUB_OUTPUT"

      - run: sudo apt install wireguard
      - run: echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}" > privatekey
      - run: sudo ip link add dev wg0 type wireguard
      - run: sudo ip address add dev wg0 10.200.0.101 peer 10.200.0.1
      - run: sudo wg set wg0 listen-port 51820 private-key privatekey peer "${{ secrets.WIREGUARD_PUBLIC_KEY }}" allowed-ips 10.200.0.0/24 endpoint "${{ secrets.PEER_ADDRESS }}":51820
      - run: sudo ip link set up dev wg0
      - run: docker load < result
      - run: docker tag onesinglecounter:latest "${{ secrets.REGISTRY }}"/onesinglecounter:latest

      - name: Add hosts to /etc/hosts
        run: |
            sudo echo "${{ secrets.PRIVATE_IP }} ${{ secrets.PRIVATE_ADDRESS }}" | sudo tee -a /etc/hosts

      - run: docker push "${{ secrets.REGISTRY }}"/onesinglecounter:latest
