name: deploy prod

on:
  tags:
    - "[0-9].[0-9]+.[0-9]+"
    - "test.[0-9].[0-9]+.[0-9]+"
  
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with: 
      deploy_env: prod
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
