name: deploy staging

on:
  push:
    branches: 
      - main
      - cicd
  tags:
    - "[0-9].[0-9]+.[0-9]+-rc"
    - "test.[0-9].[0-9]+.[0-9]+-rc"
  
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    environment: staging
    with: 
      deploy_env: staging
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
