name: deploy staging

on:
  push:
    branches: 
      - main
      - cicd
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc"
      - "test.[0-9]+.[0-9]+.[0-9]+-rc"
  
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with: 
      deploy_env: staging
    secrets:
      server_ip: ${{ secrets.SERVER_IP }}
      ssh_key: ${{ secrets.SSH_PRIVATE }}
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_port: ${{ secrets.SSH_PORT }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
