name: wireguard

on:
  workflow_call:
    inputs:
      client_ip:
        required: true
        type: string
      server_ip:
        required: true
        type: string
      port:
        required: false
        default: 51820
      allowed_ips:
        description: "Allowed IPs range (eg. '10.1.2.0/24')"
        required: true
        type: string
      server_public_key:
        required: true
        type: string
    secrets:
      server_public_ip:
        required: true
      server_private_url:
        required: true
      private_key:
        required: true

jobs:
  setup:
    name: Setup wireguard
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wireguard
      - run: echo "${{ secrets.private_key }}" > privatekey
      - run: sudo ip link add dev wg0 type wireguard
      - run: sudo ip address add dev wg0 ${{ inputs.client_ip }} peer ${{ inputs.server_ip }}
      - run: sudo wg set wg0 listen-port ${{ inputs.ports }} private-key privatekey peer "${{ inputs.server_public_key }}" allowed-ips ${{ inputs.allowed_ips }} endpoint "${{ secrets.server_public_ip }}":${{ inputs.port }}
      - run: sudo ip link set up dev wg0

      - name: Add wg hosts to /etc/hosts
        run: |
            sudo echo "${{ secrets.server_ip }} ${{ inputs.server_private_url }}" | sudo tee -a /etc/hosts
